### Example controller
GET {{url}}/example
Accept: application/json

### Example controller - long
GET {{url}}/example/long
Accept: application/json

### Example controller - cpu
GET {{url}}/example/cpu
Accept: application/json

### Example controller - memory
GET {{url}}/example/memory
Accept: application/json