spring:
  application:
    name: gabelstrapler-buggs-app

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TRACING_URL:http://localhost:4317}
    metrics:
      export:
        enabled: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

pyroscope:
  url: ${PYROSCOPE_URL:http://pyroscope:4040}
